AI_GRADE_AND_FEEDBACK_NOTICE = (
    "(This question's grade and feedback were generated by AI)"
)

INSTRUCTOR_GRADE_NOTICE = "(This question was manually graded by an instructor. The provided feedback was generated by AI)"

INSTRUCTOR_GRADE_AND_FEEDBACK_NOTICE = "(This question's grade and feedback were modified by the instructor. AI assistance may have been used to write the provided feedback.)"

INSTRUCTOR_FEEDBACK_NOTICE = "(This question's grade was generated by AI. The feedback was modified by the instructor. AI assistance may have been used to write the provided feedback.)"


def generate_ai_notice(
    ai_grade,
    ai_feedback,
    instructor_grade,
    instructor_feedback,
) -> str:
    """Generate the appropriate AI assistance notice."""
    grade_overridden = instructor_grade is not None
    feedback_overridden = (
        instructor_feedback is not None and instructor_feedback.strip()
    )

    if grade_overridden and feedback_overridden:
        return INSTRUCTOR_GRADE_AND_FEEDBACK_NOTICE

    if grade_overridden:
        return INSTRUCTOR_GRADE_NOTICE

    if feedback_overridden:
        return INSTRUCTOR_FEEDBACK_NOTICE

    return AI_GRADE_AND_FEEDBACK_NOTICE
